version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: cooperescrita_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cooperescrita
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    # para pegar o ip do container e usar no pgadmin
    # command: docker inpect <id_do_container> | grep IPAddress

  redis:
    image: redis:6
    container_name: cooperescrita_redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: cooperescrita_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
